version: "3"

services:
    # mysqldb:
    #     image: mysql:latest
    #     env_file: ./.env
    #     container_name: mysqldb
    #     ports:
    #         - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    #     networks:
    #         - DS_SQL_SPRING
    #     expose:
    #         - "33061"
    backend:
        image: dsassignment2.azurecr.io/backendimagerepository:latest
#         depends_on:
#             - mysqldb
        container_name: backend
        restart: on-failure
        env_file: ./.env
        ports:
            - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
        networks:
            - DS_SQL_SPRING
        domainname: backend-rabbit
    rabbit:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        ports:
            - $RABBIT_LOCAL_PORT:$RABBIT_DOCKER_PORT
            - $RABBIT_MANAGEMENT_LOCAL_PORT:$RABBIT_MANAGEMENT_DOCKER_PORT
        env_file: ./.env
        networks:
            - DS_SQL_SPRING
        domainname: backend-rabbit

networks:
    DS_SQL_SPRING:
        driver: bridge
